# Generated by Django 5.0.1 on 2024-01-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qavat', models.PositiveIntegerField()),
                ('raqam', models.PositiveIntegerField()),
                ('sigim', models.PositiveIntegerField()),
                ('tur', models.CharField(max_length=40)),
                ('narx', models.PositiveIntegerField()),
                ('bosh_joy_soni', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Joylashtirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.TextField(blank=True, null=True)),
                ('kelgan_sana', models.DateField()),
                ('ketgan_sana', models.DateField()),
                ('yotgan_kun_soni', models.PositiveIntegerField()),
                ('qarovchi', models.BooleanField(default=False)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.bemor')),
                ('xona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xonalar.xona')),
            ],
        ),
    ]
