# Generated by Django 5.0.1 on 2024-01-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('xonalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('tanlangan_summa', models.PositiveIntegerField()),
                ('tolandi', models.BooleanField()),
                ('created_sana', models.DateField()),
                ('tolangan_sana', models.DateField()),
                ('turi', models.CharField(max_length=40)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.bemor')),
                ('joylashtirish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xonalar.joylashtirish')),
                ('yollanma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.yollanma')),
            ],
        ),
    ]
