# Generated by Django 5.0.1 on 2024-01-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolovlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='tolangan_sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tolov',
            name='turi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
