# Generated by Django 5.0.1 on 2024-01-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolovlar', '0002_alter_tolov_tolangan_sana_alter_tolov_turi'),
    ]

    operations = [
        migrations.CreateModel(
            name='QoshimchaTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('summa', models.IntegerField()),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('tolov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolovlar.tolov')),
            ],
        ),
    ]
